services:
  tms-mongodb:
    image: mongo:7.0
    container_name: tms-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - tms-mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: TMS

  tms-mongo-express:
    image: mongo-express
    container_name: tms-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: tms-mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - tms-mongodb

volumes:
  tms-mongodb-data:
